package com.yangshuai.module.main.constant;

/**
 * @author hcp
 * Create on 2020-05-25 15:54
 */
public class Constants {
    public static  String datdata = "{\n" +
            "  \t\"msg\":\"请求成功\",\n" +
            "  \t\"succeed\":true,\n" +
            "  \t\"data\":{\n" +
            "  \t\t\"pageNo\":1,\n" +
            "  \t\t\"totalPage\":1,\n" +
            "  \t\t\"rowCntPerPage\":15,\n" +
            "  \t\t\"totalRowCount\":15,\n" +
            "  \t\t\"list\":[\n" +
            "  \t\t\t{\n" +
            "  \t\t\t\t\"commercialId\":\"950844734537388160\",\n" +
            "  \t\t\t\t\"name\":\"一一宣\",\n" +
            "  \t\t\t\t\"phone\":\"154****7771\",\n" +
            "  \t\t\t\t\"sex\":\"男\",\n" +
            "  \t\t\t\t\"requireType\":[\n" +
            "  \t\t\t\t\t\"其他\"\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"tag\":[\n" +
            "  \t\t\t\t\t\"4个跟进\"\n" +
            "  \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":1,\n" +
            " \t\t\t\t\"statusName\":\"已录入\",\n" +
            " \t\t\t\t\"openId\":\"59414680148\",\n" +
            " \t\t\t\t\"createdTm\":1649817159672\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"950844671144677504\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"154****7770\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\"2个跟进\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":1,\n" +
            " \t\t\t\t\"statusName\":\"已录入\",\n" +
            " \t\t\t\t\"openId\":\"59414680147\",\n" +
            " \t\t\t\t\"createdTm\":1649817144559\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"950844670540697728\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"154****7769\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":0,\n" +
            " \t\t\t\t\"statusName\":\"未处理\",\n" +
            " \t\t\t\t\"openId\":\"59414680146\",\n" +
            " \t\t\t\t\"createdTm\":1649817144413\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"950844166607655040\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"154****7768\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":0,\n" +
            " \t\t\t\t\"statusName\":\"未处理\",\n" +
            " \t\t\t\t\"openId\":\"59414680145\",\n" +
            " \t\t\t\t\"createdTm\":1649817024268\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"950844166012063872\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"154****5767\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":0,\n" +
            " \t\t\t\t\"statusName\":\"未处理\",\n" +
            " \t\t\t\t\"openId\":\"59414680144\",\n" +
            " \t\t\t\t\"createdTm\":1649817024125\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"950844102594187392\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"154****5767\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":0,\n" +
            " \t\t\t\t\"statusName\":\"未处理\",\n" +
            " \t\t\t\t\"openId\":\"59414680143\",\n" +
            " \t\t\t\t\"createdTm\":1649817009005\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"950844038974984320\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"154****5767\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":0,\n" +
            " \t\t\t\t\"statusName\":\"未处理\",\n" +
            " \t\t\t\t\"openId\":\"59414680142\",\n" +
            " \t\t\t\t\"createdTm\":1649816993835\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"949152007634473088\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"183****5766\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":0,\n" +
            " \t\t\t\t\"statusName\":\"未处理\",\n" +
            " \t\t\t\t\"openId\":\"59414680124\",\n" +
            " \t\t\t\t\"createdTm\":1649413582111\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"948436124293320832\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"188****5766\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":1,\n" +
            " \t\t\t\t\"statusName\":\"已录入\",\n" +
            " \t\t\t\t\"openId\":\"59414680123\",\n" +
            " \t\t\t\t\"createdTm\":1649242902241\n" +
            " \t\t\t},\n" +
            " \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"948413451207102592\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"188****5766\",\n" +
            " \t\t\t\t\"sex\":\"男\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            "  \t\t\t\t\"status\":1,\n" +
            "  \t\t\t\t\"statusName\":\"已录入\",\n" +
            "  \t\t\t\t\"openId\":\"59414680121\",\n" +
            "  \t\t\t\t\"createdTm\":1649237496556\n" +
            "  \t\t\t},\n" +
            "  \t\t\t{\n" +
            "  \t\t\t\t\"commercialId\":\"948406533612818560\",\n" +
            "  \t\t\t\t\"name\":\"一一宣\",\n" +
            "  \t\t\t\t\"phone\":\"196****5766\",\n" +
            "  \t\t\t\t\"sex\":\"男\",\n" +
            "  \t\t\t\t\"requireType\":[\n" +
            "  \t\t\t\t\t\"其他\"\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"tag\":[\n" +
            "  \t\t\t\t\t\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            "  \t\t\t\t\"status\":0,\n" +
            "  \t\t\t\t\"statusName\":\"未处理\",\n" +
            "  \t\t\t\t\"openId\":\"59414680111\",\n" +
            "  \t\t\t\t\"createdTm\":1649235847273\n" +
            "  \t\t\t},\n" +
            "  \t\t\t{\n" +
            "  \t\t\t\t\"commercialId\":\"948399419217596544\",\n" +
            "  \t\t\t\t\"name\":\"一一宣\",\n" +
            "  \t\t\t\t\"phone\":\"176****5766\",\n" +
            "  \t\t\t\t\"sex\":\"男\",\n" +
            "  \t\t\t\t\"requireType\":[\n" +
            "  \t\t\t\t\t\"其他\"\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"tag\":[\n" +
            "  \t\t\t\t\t\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            "  \t\t\t\t\"status\":0,\n" +
            "  \t\t\t\t\"statusName\":\"未处理\",\n" +
            "  \t\t\t\t\"openId\":\"59414680108\",\n" +
            "  \t\t\t\t\"createdTm\":1649234151069\n" +
            "  \t\t\t},\n" +
            "  \t\t\t{\n" +
            "  \t\t\t\t\"commercialId\":\"943330809759584384\",\n" +
            "  \t\t\t\t\"name\":\"一一宣\",\n" +
            "  \t\t\t\t\"phone\":\"145****5766\",\n" +
            "  \t\t\t\t\"sex\":\"未知\",\n" +
            "  \t\t\t\t\"requireType\":[\n" +
            "  \t\t\t\t\t\"其他\"\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"tag\":[\n" +
            "  \t\t\t\t\t\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            "  \t\t\t\t\"status\":2,\n" +
            "  \t\t\t\t\"statusName\":\"已释放\",\n" +
            "  \t\t\t\t\"openId\":\"5941468098\",\n" +
            "  \t\t\t\t\"createdTm\":1648025700400\n" +
            "  \t\t\t},\n" +
            "  \t\t\t{\n" +
            "  \t\t\t\t\"commercialId\":\"943330368338448512\",\n" +
            "  \t\t\t\t\"name\":\"一一宣\",\n" +
            "  \t\t\t\t\"phone\":\"145****5766\",\n" +
            "  \t\t\t\t\"sex\":\"未知\",\n" +
            "  \t\t\t\t\"requireType\":[\n" +
            "  \t\t\t\t\t\"其他\"\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"tag\":[\n" +
            "  \t\t\t\t\t\n" +
            "  \t\t\t\t],\n" +
            "  \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            "  \t\t\t\t\"status\":2,\n" +
            "  \t\t\t\t\"statusName\":\"已释放\",\n" +
            "  \t\t\t\t\"openId\":\"5941468898\",\n" +
            "  \t\t\t\t\"createdTm\":1648025595160\n" +
            "  \t\t\t},\n" +
            "  \t\t\t{\n" +
            " \t\t\t\t\"commercialId\":\"943319982356746368\",\n" +
            " \t\t\t\t\"name\":\"一一宣\",\n" +
            " \t\t\t\t\"phone\":\"151****5759\",\n" +
            " \t\t\t\t\"sex\":\"未知\",\n" +
            " \t\t\t\t\"requireType\":[\n" +
            " \t\t\t\t\t\"其他\"\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"tag\":[\n" +
            " \t\t\t\t\t\n" +
            " \t\t\t\t],\n" +
            " \t\t\t\t\"sourceName\":\"58-微聊(自动)\",\n" +
            " \t\t\t\t\"status\":2,\n" +
            " \t\t\t\t\"statusName\":\"已释放\",\n" +
            " \t\t\t\t\"openId\":\"59114098\",\n" +
            " \t\t\t\t\"createdTm\":1648023118946\n" +
            " \t\t\t}\n" +
            " \t\t],\n" +
            " \t\t\"order\":null,\n" +
            " \t\t\"condition\":null\n" +
            " \t},\n" +
            " \t\"code\":\"200\",\n" +
            " \t\"requestId\":null\n" +
            " }";
}
